name: Build-Env Docker Image

on:
  push:
    branches: master
    paths:
    - '**Dockerfile'
    - '**docker.yml'
#  workflow_dispatch:
#  schedule:
#    - cron: '30 11 20 */3 *'

jobs:
  build-env-image:
    runs-on: ubuntu-24.04
    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        env:
          REGISTRY_IMAGE: ghcr.io/${{ env.OWNER_LC }}/vs-fltk
        with:
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=${{ env.REGISTRY_IMAGE }}:build-env-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_IMAGE }}:build-env-buildcache,mode=max
